apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deployment
  labels:
    app: greeting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting-container
          image: rajeshrajatv/springboot-githubactions-k8s:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          imagePullPolicy: Always
          volumeMounts:
            - name: jar-volume
              mountPath: /app/data
      volumes:
        - name: jar-volume
          persistentVolumeClaim:
            claimName: jar-pvc
