apiVersion: v1
kind: PersistentVolume
metadata:
  name: jar-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:  # ⚠️ Only use hostPath for local testing. Replace with cloud storage class in production.
    path: "/mnt/data/jars"
